apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
  namespace: infra
spec:
  capacity:
    storage: {{ .Values.postgres.storage }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: postgres-static
  hostPath:
    path: /data/postgres
